### ISSUE TITLE
Fact sheets/broken link

### ISSUE THREAD

**Issue by troydash** [DashInvests/dif-communication#4]
Hi,
The link to the fact sheet on this page is broken:
https://github.com/DashInvests/dif-communication/blob/master/weekly-updates/5-7-2020.md

Also, can all the fact sheets be hosted here on github as well instead of google?
Thanks

**Comment by CryptoAmanda** [comment]
Hi, troydash.

Thanks for pointing this out. I have hosted the file here on Github, as suggested, and changed the hyperlink to point to it. Please let me know that this works for you.

Thanks,
Amanda

**Comment by troydash** [comment]
Awesome, thank you!
